-- local o = vim.opt_local
-- o.expandtab = true
-- o.tabstop = 4
-- o.shiftwidth = 4
-- o.softtabstop = 4
-- -- If HTML still over-indents, uncomment one or both:
-- o.indentexpr = ""      -- disable Treesitter/HTML custom indent
-- o.smartindent = false  -- belt-and-suspenders, this 
